# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Yuqi/KOF-94/lab6_1/lab6_1.srcs/sources_1/ip/mai_forward_rom/mai_forward_rom.xci
# IP: The module: 'mai_forward_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Yuqi/KOF-94/lab6_1/lab6_1.gen/sources_1/ip/mai_forward_rom/mai_forward_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mai_forward_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Yuqi/KOF-94/lab6_1/lab6_1.srcs/sources_1/ip/mai_forward_rom/mai_forward_rom.xci
# IP: The module: 'mai_forward_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Yuqi/KOF-94/lab6_1/lab6_1.gen/sources_1/ip/mai_forward_rom/mai_forward_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mai_forward_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
