@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
REM Generated by Vivado on Mon Nov 20 17:36:17 -0600 2023
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: compile.bat
REM
REM ****************************************************************************

set xv_cxl_lib_path="C:/Xilinx/Vivado/2022.2/data/xsim"
set xv_cpt_lib_path=""
set xv_ext_lib_path=""
set xv_boost_lib_path="C:/Xilinx/Vivado/2022.2/tps/boost_1_72_0"

REM compile C design sources
echo "xsc -c --gcc_compile_options "-I%xv_boost_lib_path%" -work xil_defaultlib -f mb_usb_hdmi_top_c.prj"
call xsc  -c --gcc_compile_options "-I%xv_boost_lib_path%" -work xil_defaultlib -f mb_usb_hdmi_top_c.prj 2> xsc_err.log
call type xsc.log >> compile.log
call type xsc_err.log >> compile.log
call type xsc_err.log
REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -prj mb_usb_hdmi_top_vlog.prj"
call xvlog  --incr --relax -L uvm -prj mb_usb_hdmi_top_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
REM compile VHDL design sources
echo "xvhdl --incr --relax -prj mb_usb_hdmi_top_vhdl.prj"
call xvhdl  --incr --relax -prj mb_usb_hdmi_top_vhdl.prj -log xvhdl.log
call type xvhdl.log >> compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
